/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooq;


import com.example.demo.jooq.tables.Book;


/**
 * Convenience access to all tables in jooq.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.book</code>.
     */
    public static final Book BOOK = Book.BOOK;
}
